- name: Configure local workstation
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    go_version: "1.13.5"
    kubectl_version: "v1.19.4"
    fonts_dir: "{% if ansible_system == 'Linux' %}{{ ansible_env.HOME }}/.local/share/fonts{% elif ansible_system == 'Darwin' %}{{ ansible_env.HOME }}/Library/Fonts{% endif %}"
    localbin_dir: "{{ ansible_env.HOME }}/.local/bin"
    gitconfig_dir: "{{ ansible_env.HOME }}/.local/git"
    post_install: |
      You need to change your current shell to use zsh.
      With running the following commands:
           chsh -s $(which zsh)

      You also need to run keybase with running the following commands:
            run_keybase

      Then after that you need to import your current pgp key from keybase,
      with running the following commands:
            keybase pgp export -s | gpg --import

  tasks:
  - include: ansible/common.yaml
    tags:
      - common
      - packages

  - include: ansible/debian_packages.yaml
    tags:
      - packages

  - include: ansible/fonts.yaml
    tags:
      - fonts

  - include: ansible/zsh.yaml
    tags:
      - zsh

  - include: ansible/toolkit.yaml
    tags:
      - toolkit

  - include: ansible/languages.yaml
    tags:
      - proglang

  - include: ansible/kubectl.yaml
    tags:
      - kubectl

  - include: ansible/cloud.yaml
    tags:
      - cloud

  - name: "Post installation"
    debug:
      msg: "{{ post_install.split('\n') }}"
    tags:
      - common
