go_version: "1.13.5"
kubectl_version: "v1.19.4"
sops_version: "v3.6.1"
fonts_dir: "{% if ansible_system == 'Linux' %}{{ ansible_env.HOME }}/.local/share/fonts{% elif ansible_system == 'Darwin' %}{{ ansible_env.HOME }}/Library/Fonts{% endif %}"
localbin_dir: "{{ ansible_env.HOME }}/.local/bin"
gitconfig_dir: "{{ ansible_env.HOME }}/.local/git"

post_install: |
  You need to change your current shell to use zsh.
  With running the following commands:
        chsh -s $(which zsh)

  You also need to run keybase with running the following commands:
        run_keybase

  Then after that you need to import your current pgp key from keybase,
  with running the following commands:
        keybase pgp export -s | gpg --import

powerline_fonts: no
nerd_fonts: yes

packages:
  - wget
  - curl
  - git
  - zsh
  - gnupg2
  - tmux
  - vim
  - unzip
  - fontconfig
  - ca-certificates
  - apt-transport-https
  - rsync
  - make
  - openssh-client
  - build-essential
  - llvm
  - tk-dev
  - xz-utils
  - zlib1g-dev
  - libssl-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libffi-dev
  - liblzma-dev
  - python3-openssl
  - python3-dev
  - shellcheck
  - dnsutils
  - oathtool
  - procps
  - docker.io
