- name: "Ensure directory exist"
  file:
    path: "{{ item }}"
    state: "directory"
    recurse: yes
  loop:
  - "{{ localbin_dir }}"
  - "{{ gitconfig_dir }}"
  - "{{ fonts_dir }}"
  tags:
    - directory

- name: Install required packages (APT)
  apt:
    pkg: "{{ packages }}"
    state: latest
    update_cache: yes
  become: yes
  when: ansible_system == "Linux" and ansible_os_family == "Debian"
  tags:
    - packages

- name: Install required packages (YUM)
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  become: yes
  when: ansible_system == "Linux" and ansible_os_family == "RedHat"
  tags:
    - packages

- name: Download personal dotfiles
  git:
    repo: "https://github.com/ardikabs/dotfiles.git"
    dest: /tmp/dotfiles
    version: master
    update: yes
    force: yes
  tags:
    - dotfiles
